### ISSUE TITLE
PROJECT_VERSION_FROM_GIT with git path parameter

### ISSUE THREAD

**Issue by troian** [Oleh-Kravchenko/cmake-version4git#2]
Sometimes git repo to version against is not a root PROJECT_DIR likewise using **repo tool**
Would be nice to have smth like that PROJECT_VERSION_FROM_GIT(${<PROJECT_GIT_ROOT>})

**Comment by Oleh-Kravchenko** [comment]
Thanks Artur for idea!
Implemented by a3489af6a55bd6783a059c746b721f51b7971c67
